### PR TITLE
A couple of small fixes to get the configure.sh working.

### PR DESCRIPTION
**Pull request by aaroncoville**
First, thanks for all of the awesome work! I hope these proposed changes help out even a little.

Fix for #21 - updates the source to use the remote prompt file, updates the execution command in the README.md

I moved zshZInstall after ohmyzshInstall as zshZInstall created the .oh-my-zsh directory giving a false positive when checking if oh-my-zsh is already installed.

The success call for logging output was missing on the zsh-syntax-highlighting cloning line causing an error.

This fixes the first few gotchas I had when working my fork of your repository.

Right now, when doing a fresh install on macOS ohmyzsh immediately loads into the terminal stopping script execution. I'm not sure how to get around this yet, right now if you are doing a fresh install you have to run the script and then run it again after ohmyzsh takes over your terminal. File this under known issues for now.

### CODE REVIEW

**Comment by aaroncoville** [comment]
Added another small one. I assume this worked at one point but I kept getting $ZSH_CUSTOM as an unbound variable. I noticed that the value was set explicitly for powerlevel9k (and not using $ZSH_CUSTOM) so i followed suit for powerlevel10k as it seemed to be the easiest solution.

**Comment by aaroncoville** [comment]
Permission denied when trying to copy the font on macOS Catalina. Added sudo.

**Comment by aaroncoville** [comment]
Added a fix to prevent ohmyzsh installation from stopping script execution. Per [this document](https://github.com/ohmyzsh/ohmyzsh#unattended-install).

As a side note - I know this is a lot for a single PR but I can't fork the repo more than once and my base branch already has some of my personal customizations. So, I put myself in a position where the only branch I can make changes to submit back to you is this one. Maybe I'm missing something obvious?

**Comment by jldeen** [comment]
Thank you so much for this! This looks great! 

Note: I will be removing support for Powerlevel9k as Ben has archived the project and redirected guidance for all to use Powerlevel10k. This project already supports both. I'll be sure to note your findings on $ZSH_CUSTOM.

**Pull request merged**
